- name:
  hosts: localhost
  tasks:
    - name: build the image for 1st website with dockerfile
      docker_image:
        name: docker-website1
        build:
          path: /home/ray/ansible-uebung/ansible-gruppenarbeit/docker-image-nginx-website/website1
        source: build
    - name: build the image for 2nd website with dockerfile
      docker_image:
        name: docker-website2
        build:
          path: /home/ray/ansible-uebung/ansible-gruppenarbeit/docker-image-nginx-website/website2
        source: build
    - name: build the image for 3rd website with dockerfile
      docker_image:
        name: docker-website3
        build:
          path: /home/ray/ansible-uebung/ansible-gruppenarbeit/docker-image-nginx-website/website3
        source: build
